---
- name: Ensure the required apt packages are installed
  ansible.builtin.apt:
    name:
      - ca-certificates
      - curl
      - gnupg
      - lsb-release
    state: present
    update_cache: yes
  when: ansible_os_family == "Debian"

- name: Add The Docker GPG key (Debian/Ubuntu)
  ansible.builtin.apt_key:
    url: "https://download.docker.com/linux/{{ ansible_distribution | lower }}/gpg"
    state: present
  when: ansible_os_family == "Debian"

- name: Add The Docker repository (Debian/Ubuntu)
  ansible.builtin.apt_repository:
    repo: "deb [arch=amd64] https://download.docker.com/linux/{{ ansible_distribution | lower }} {{ ansible_distribution_release }} stable"
    state: present
  when: ansible_os_family == "Debian"

- name: Install The Docker engine (Debian/Ubuntu)
  ansible.builtin.apt:
    name:
      - docker-ce
      - docker-ce-cli
      - containerd.io
    state: present
    update_cache: yes
  when: ansible_os_family == "Debian"

- name: Install the yum utils (CentOS)
  ansible.builtin.yum:
    name: yum-utils
    state: present
  when: ansible_os_family == "RedHat"

- name: Add The Docker repository (CentOS)
  ansible.builtin.get_url:
    url: https://download.docker.com/linux/centos/docker-ce.repo
    dest: /etc/yum.repos.d/docker-ce.repo
  when: ansible_os_family == "RedHat"

- name: Install The Docker engine (CentOS)
  ansible.builtin.yum:
    name:
      - docker-ce
      - docker-ce-cli
      - containerd.io
    state: present
  when: ansible_os_family == "RedHat"

- name: Enable and start Docker service
  ansible.builtin.service:
    name: docker
    state: started
    enabled: yes


- name: Deploy The Apache container
  community.docker.docker_container:
    name: "{{ apache.container_name }}"
    image: "{{ apache.image }}"
    state: started
    restart_policy: always
    ports:
      - "{{ apache.port }}:80"
    docker_host: "unix:///var/run/docker.sock"
